# Numpy

## Task 1

You should import the necessary libraries. You will use `numpy` and `sys` libraries.


> Don't forget to import `numpy` in the short form.

In [19]:
import sys
import time

import numpy as np

## Task 2

Create arrays with using Python default syntax and using `numpy`. Also, print the size of the arrays in bytes. You should use `sys` library for this task.

Requirements for arrays:
* length of the array should be `1000`;
* array should contain zeros;
* the second array should be generated by `numpy` library, and should have as little memory as possible.

In [8]:
python_array = [0] * 1000
python_array_size = sys.getsizeof(python_array) + sum(sys.getsizeof(item) for item in python_array)
print(python_array_size)

36056


In [7]:
numpy_array = np.zeros(1000, dtype=np.uint8)
numpy_array_size = numpy_array.nbytes
print(numpy_array_size)

1000


numpy_array_size = numpy_array.nbytes## Task 3

Write manually a small float array using `numpy` syntax number should be in the range from `0` to `10.0`. Also, you should get the first, the third, and the last elements of the array using multi-indexing.

Requirements:
* length of the array should be from `5` to `10`.

In [9]:
float_array = np.array([1.2, 3.4, 5.6, 7.8, 9.0], dtype=float)
selected_elements = float_array[[0, 2, -1]]
print(selected_elements)

[1.2 5.6 9. ]


## Task 4

You have the array `array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])` using multi-indexing you should summarize a subsequence of an array and get the `27` as the result.

In [10]:
array = np.array([2.3, 7.8, 3.2, 1.1, 5.8, 9.5, 17.6, 11.1])
selected_elements = array[[0,1, 4, 7]]
sum_of_selected = selected_elements.sum()
print(sum_of_selected)
# write your code here

27.0


## Task 5

You have a matrix `A`:

```python
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])
```

Follow the comments in the next cells and write the code.

In [12]:
A = np.array([
    [1, 6],
    [2, 8],
    [3, 11],
    [3, 10],
    [1, 7]
])

### Task 5.1 Find the mean for each column by `x` axis

In [13]:
np.mean(A, axis=1)

array([3.5, 5. , 7. , 6.5, 4. ])

### Task 5.2 Get the standard deviation by `y` axis

In [21]:
np.std(A, axis=0)

array([0.89442719, 1.8547237 ])

### Task 5.3 Get the sum of all elements in `A` by `y` axis

In [14]:
np.sum(A, axis=0)

array([10, 42])

### Task 5.4 Get the following result using multi-dim selection:

```python
[
    [1, 6],
    [2, 8],
 ]
```

In [23]:
A[:2, :]

array([[1, 6],
       [2, 8]])

##  Task 5.5. Get the following result using multi-dim selection:
```python
[
    [1, 6],
    [3, 11],
    [1, 7]
 ]
```

In [24]:
A[[0, 2, 4], :]

array([[ 1,  6],
       [ 3, 11],
       [ 1,  7]])

## Task 6

Rewrite Python code to `numpy` code. Also, estimate the time of execution for both implementations.

> Please, note: `unknown_signature` this name just hide the real name of the function, to make the task more complicated.

### Task 6.1

In [24]:
# Python code
start_time = time.time()
python_array = [i for i in range(1000000)]
python_execution_time = time.time() - start_time
print(len(python_array))
print(python_execution_time)

1000000
0.10043191909790039


In [23]:
start_time = time.time()
numpy_array = np.arange(1000000)
numpy_execution_time = time.time() - start_time
print(len(numpy_array))
print(numpy_execution_time)

1000000
0.0


### Task 6.2

In [27]:
# Python code
def unknown_signature(vector1, vector2):
    result = 0
    for i in range(len(vector1)):
        result += vector1[i] * vector2[i]
    return result

vector1 = [1, 2, 3]
vector2 = [4, 5, 6]

start_time = time.time()
result = unknown_signature(vector1, vector2)
python_execution_time = time.time() - start_time
print(result)
print(python_execution_time)

32
0.0


In [28]:
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
start_time = time.time()
result_np = np.dot(vector1, vector2)
numpy_execution_time = time.time() - start_time
print(result_np)
print(numpy_execution_time)

32
0.0


### Task 6.3

In [29]:
# Python code
def unknown_signature(matrix1, matrix2):
    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix1[i])):
            row.append(matrix1[i][j] * matrix2[i][j])
        result.append(row)
    return result

matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

start_time = time.time()
result = unknown_signature(matrix1, matrix2)
python_execution_time = time.time() - start_time
print(result)
print(python_execution_time)

[[5, 12], [21, 32]]
0.0


In [30]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
start_time = time.time()
result_np = matrix1 * matrix2
numpy_execution_time = time.time() - start_time
print(result_np)
print(numpy_execution_time)

[[ 5 12]
 [21 32]]
0.0


### Task 6.4

In [31]:
# Python code
def unknown_signature(lst):
    total = 0
    for num in lst:
        total += num
    result = total / len(lst)
    return result

lst = [1, 2, 3, 4, 5]

start_time = time.time()
result = unknown_signature(lst)
python_execution_time = time.time() - start_time
print(result)
print(python_execution_time)

3.0
0.0


In [32]:
lst = np.array([1, 2, 3, 4, 5])
start_time = time.time()
result_np = np.mean(lst)
numpy_execution_time = time.time() - start_time
print(result_np)
print(numpy_execution_time)

3.0
0.0


## Task 7

Rewrite Python code to `numpy` code (Masks).

### Task 7.1

In [36]:
# Python code
def unknown_signature(lst, mask, new_value):
    for i in range(len(lst)):
        if mask[i]:
            lst[i] = new_value

lst = [1, 2, 3, 4, 5]
mask = [True, False, True, False, True]
new_value = 0
unknown_signature(lst, mask, new_value)
print(lst)

[0, 2, 0, 4, 0]


In [37]:
def unknown_signature(lst, mask, new_value):
    lst[mask] = new_value

lst = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
new_value = 0

unknown_signature(lst, mask, new_value) 
print(lst)

[0 2 0 4 0]


### Task 7.2

In [38]:
# Python code
def unknown_signature(lst1, lst2):
    bitwise_complement = [~x for x in lst1]
    bitwise_and = [x & y for x, y in zip(lst1, lst2)]
    bitwise_or = [x | y for x, y in zip(lst1, lst2)]
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
print("Bitwise complement:", result_bitwise_complement)
print("Bitwise AND:", result_bitwise_and)
print("Bitwise OR:", result_bitwise_or)

Bitwise complement: [-6, -3, -8, -5, -10]
Bitwise AND: [1, 2, 1, 0, 8]
Bitwise OR: [7, 6, 7, 12, 11]


In [39]:
def unknown_signature(lst1, lst2):
    lst1 = np.array(lst1)
    lst2 = np.array(lst2)
    bitwise_complement = ~lst1
    bitwise_and = lst1 & lst2
    bitwise_or = lst1 | lst2
    return bitwise_complement, bitwise_and, bitwise_or

list1 = [5, 2, 7, 4, 9]
list2 = [3, 6, 1, 8, 10]
result_bitwise_complement, result_bitwise_and, result_bitwise_or = unknown_signature(list1, list2)
print("Bitwise complement:", result_bitwise_complement)
print("Bitwise AND:", result_bitwise_and)
print("Bitwise OR:", result_bitwise_or)

Bitwise complement: [ -6  -3  -8  -5 -10]
Bitwise AND: [1 2 1 0 8]
Bitwise OR: [ 7  6  7 12 11]


### Task 7.3 Optional

In [40]:
# Python code
def unknown_signature(lst):
    result = []
    for num in lst:
        if num % 2 == 0 and (num % 3 == 0 or num > 10):
            modified_num = (num ^ 7) + 2
            result.append(modified_num)
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_python_style = unknown_signature(my_list)
print(result_python_style)

[3, 13, 11, 21]


In [41]:
def unknown_signature(lst):
    lst = np.array(lst)
    mask = (lst % 2 == 0) & ((lst % 3 == 0) | (lst > 10))
    modified_lst = (lst ^ 7) + 2
    result = modified_lst[mask]
    return result

my_list = [6, 9, 12, 14, 17, 20]
result_numpy_style = unknown_signature(my_list)
print(result_python_style)

[3, 13, 11, 21]
